name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: zhutmost/setup-mill@main
      - name: Publish
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME}}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
        run: mill -i mill.scalalib.SonatypeCentralPublishModule/publishAll --shouldRelease false --publishArtifacts 'opengraph4s[_].publishArtifacts'
